server:
  port: 8080

grpc:
  server:
    port: 8087

spring:
  application:
    name: sensor-service
  main:
    allow-bean-definition-overriding: true
  data:
    elasticsearch:
      repositories:
        enabled: true

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4317
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    enable:
      jvm: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  health:
    elasticsearch:
      enabled: false


endpoints:
  payment:
    url: htt://payment.xpto.com