grpc:
  server:
    shutdown-grace-period: 0

spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris:
      - http://localhost:9200
eureka:
  client:
    register-with-eureka: false