server:
  port: 8080

grpc:
  server:
    port: 8081

spring:
  application:
    name: sensor-service
  main:
    allow-bean-definition-overriding: true

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include:
          - '*'
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  health:
    elasticsearch:
      enabled: false
