name: Sensor Service CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sensor-service
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Add Gradle Permission
        run: chmod +x ./gradlew    

      - name: Compile
        run: ./gradlew clean compileTestJava

      - name: Test
        run: ./gradlew test

      - name: Build
        run: ./gradlew build