server:
  port: 8082

grpc:
  server:
    port: 8085

spring:
  application:
    name: location-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    openfeign:
      micrometer:
        enabled: true
      okhttp:
        enabled: true

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4317
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  health:
    elasticsearch:
      enabled: false


feign:
  client:
    config:
      location-client:
        logger-level: FULL